### ISSUE TITLE
Extend URL cleaning 

### ISSUE THREAD

**Issue by leanne1** [buildit/storybook-addon-blabbr#14]
stories can be:
"really nice dropdown"
We need to clean the story name to a url friendly path @jon-ec what format should whitespace substitute in a url path? `-` or `_` etc.

**Comment by jon-ec** [comment]
best solution would be to remove all special characters and replace spaces with '_'

**Comment by leanne1** [comment]
https://github.com/buildit/storybook-addon-reviewer/pull/17
