### ISSUE TITLE
Show blabbr panel on click in story

### ISSUE THREAD

**Issue by panosvoudouris** [buildit/storybook-addon-blabbr#42]
When the comments button is clicked in the story the blabbr panel should come into focus (if not already in focus).

**Comment by panosvoudouris** [comment]
Currently there is nothing in the API to allow this.

**Comment by leanne1** [comment]
I had a look in the source code and couldn't find a way to hack this other than change the `downPanel` query string and force a window refresh

**Comment by panosvoudouris** [comment]
Storybook doesn't support this so let's leave it.
