### ISSUE TITLE
Comments show up in the wrong story

### ISSUE THREAD

**Issue by panosvoudouris** [buildit/storybook-addon-blabbr#61]
It looks like the submit button sends comments to the previous story viewed, not the current.

Switching through stories seems to sometimes update, sometimes not the comments and submitting a comment then reloading seems a bit random. There is an illusion of it working if you just stay in the default button story.

**Comment by jon-ec** [comment]
PR created - the branch was created off your lint fix branch to avoid conflicts so merge that one first
