### ISSUE TITLE
Parse hyperlinks

### ISSUE THREAD

**Issue by panosvoudouris** [buildit/storybook-addon-blabbr#67]
Parse hyperlinks in comments and display as links.

**Comment by panosvoudouris** [comment]
This is probably high on the list as it would allow people to link to sketch or other systems...?

**Comment by jon-ec** [comment]
Might even be worth adding a simple WYSIWYG editor component? https://www.npmjs.com/package/wysiwyg-editor-react

I'm awaiting Bluemix access atm, but will let you know once I'm in and we can try get this into Payments :)

**Comment by panosvoudouris** [comment]
Done with https://github.com/buildit/storybook-addon-blabbr/pull/69
